spring:
  application:
    name: VMonClick

  cassandra:
    keyspace-name: "kp"
    contact-points:
      - "18.230.240.141"
      - "54.207.33.9"
      - "54.94.24.166"
    schema-action: CREATE_IF_NOT_EXISTS
    username: scylla
    password: vFgcj9k4StLZ1OU
    local-datacenter: AWS_SA_EAST_1
    connection:
      connect-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080


#! neo4j: r@@t12345

springdoc:
  swagger-ui:
    path: /api
