spring:
  application:
    name: VMonClick

  cassandra:
    keyspace-name: "kp"
    contact-points:
      - "node-0.aws-us-east-1.bfd31962b5dbed133c87.clusters.scylla.cloud"
      - "node-1.aws-us-east-1.bfd31962b5dbed133c87.clusters.scylla.cloud"
      - "node-2.aws-us-east-1.bfd31962b5dbed133c87.clusters.scylla.cloud"
    schema-action: CREATE_IF_NOT_EXISTS
    username: scylla
    password: jUsp3yiC75qWFvg
    local-datacenter: AWS_US_EAST_1
    connection:
      connect-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

#! neo4j: r@@t12345

springdoc:
  swagger-ui:
    path: /api
