spring:
  application:
    name: VMonClick

  cassandra:
    keyspace-name: "kp"
    contact-points:
      - "node-0.aws-us-east-1.6efb60f0387a1c7eeaa8.clusters.scylla.cloud"
      - "node-1.aws-us-east-1.6efb60f0387a1c7eeaa8.clusters.scylla.cloud"
      - "node-2.aws-us-east-1.6efb60f0387a1c7eeaa8.clusters.scylla.cloud"
    schema-action: CREATE_IF_NOT_EXISTS
    username: scylla
    password: 8Zbs9ygUS3tmziu
    local-datacenter: AWS_US_EAST_1
    connection:
      connect-timeout: PT10S
      init-query-timeout: PT10S
    request:
      timeout: PT10S
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api

jwt:
  token:
    secret: "46c8dcd2061bfe336e70802683e77d5c32de8e00b6e4251cb07eebe5965a87b7"
