spring:
  application:
    name: VMonClick

  cassandra:
    keyspace-name: "kp"
    contact-points:
      - "node-0.aws-sa-east-1.575f197665f85a77a519.clusters.scylla.cloud"
      - "node-1.aws-sa-east-1.575f197665f85a77a519.clusters.scylla.cloud"
      - "node-2.aws-sa-east-1.575f197665f85a77a519.clusters.scylla.cloud"
    schema-action: CREATE_IF_NOT_EXISTS
    username: scylla
    password: vFgcj9k4StLZ1OU
    local-datacenter: AWS_SA_EAST_1
    connection:
      connect-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api
